name: 'Prepare Rspack Binding'
description: 'Checkout, build, and upload rspack native bindings'
inputs:
  repository:
    description: 'The rspack repository to use'
    required: true
    default: 'web-infra-dev/rspack'
  path:
    description: 'Destination path to clone'
    required: true
    default: 'workspace/rspack'
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: true
    default: 'main'
  node-version:
    description: 'The version of Node.js to set up'
    required: true
    default: '22'
outputs:
  artifact-name:
    description: 'The name of the uploaded artifact'
runs:
  using: composite
  steps:
    - name: Checkout Rspack repo
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        repository: ${{ inputs.repository }}
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: ${{ inputs.node-version }}
    - shell: bash
      name: Install package manager
      run: |
        cd ${{ inputs.path }}
        npm install -g corepack@latest --force
        echo "Corepack version: $(corepack --version)"
        corepack enable
    - id: rust-cache
      uses: MasterworksIO/action-local-cache@7fb1f91c4eeb3226ecbad42d686334d940167f61 # 2
      with:
        path: '${{ inputs.path }}/target'
    - name: Show Rust Cache
      if: steps.rust-cache.outputs.cache-hit == 'true'
      shell: bash
      run: ls -lah ${{ inputs.path }}/target
    - name: Build Rspack
      shell: bash
      env:
        TARGET_CC: clang
      run: |
        cd ${{ inputs.path }}
        pnpm i --frozen-lockfile
        pnpm --filter @rspack/binding install --frozen-lockfile
        cargo codegen
        pnpm run build:binding:release
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: binding-linux-x64-gnu
        path: ${{ inputs.path }}/crates/node_binding/*.node
