name: 'Build Rslint'
description: 'Checkout and install rslint'
inputs:
  repository:
    description: 'The rslint repository to use'
    required: true
    default: 'web-infra-dev/rslint'
  path:
    description: 'Destination path to the rslint repository'
    required: true
    default: 'workspace/rslint'
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: true
    default: 'main'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - shell: bash
      name: Install package manager
      run: |
        npm install -g corepack@latest --force
        echo "Corepack version: $(corepack --version)"
        corepack enable

    - name: Checkout Rslint repo
      uses: actions/checkout@v5
      with:
        repository: ${{ inputs.repository }}
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ inputs.path }}
        pnpm install
