name: 'Build Rsbuild'
description: 'Checkout, build rsbuild'
inputs:
  repository:
    description: 'The rsbuild repository to use'
    required: true
    default: 'web-infra-dev/rsbuild'
  path:
    description: 'Destination path to the rsbuild repository'
    required: true
    default: 'workspace/rsbuild'
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: true
    default: 'main'
outputs:
  artifact-name:
    description: 'The name of the uploaded artifact'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: 22.22.3
    - shell: bash
      name: Install package manager
      run: |
        npm install -g corepack@latest --force
        echo "Corepack version: $(corepack --version)"
        corepack enable

    - name: Checkout Rsbuild repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        repository: ${{ inputs.repository }}
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}
    - name: Build Rsbuild
      shell: bash
      run: |
        cd ${{ inputs.path }}
        pnpm i
        node --run build
