name: 'Build Rsbuild'
description: 'Checkout, build rsbuild'
inputs:
  repository:
    description: 'The rsbuild repository to use'
    required: true
    default: 'web-infra-dev/rsbuild'
  path:
    description: 'Destination path to the rsbuild repository'
    required: true
    default: 'workspace/rsbuild'
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: true
    default: 'main'
outputs:
  artifact-name:
    description: 'The name of the uploaded artifact'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: 24.18.0
    - shell: bash
      name: Install package manager
      run: |
        npm install -g corepack@latest --force
        echo "Corepack version: $(corepack --version)"
        corepack enable

    - name: Checkout Rsbuild repo
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      with:
        repository: ${{ inputs.repository }}
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}
    - name: Build Rsbuild
      shell: bash
      run: |
        cd ${{ inputs.path }}
        pnpm i
        node --run build
