name: "ecosystem_ci_per_commit"
description: "Trigger downstream ecosystem CI for commits and comment on failures"

inputs:
  github-token:
    description: "Token with access to the downstream ecosystem CI repository"
    required: true
  ecosystem-owner:
    description: "Owner of the downstream ecosystem CI repository"
    required: false
    default: "rspack-contrib"
  ecosystem-repo:
    description: "Repository containing the downstream workflow"
    required: true
  workflow-file:
    description: "Workflow file to execute in the downstream repository"
    required: true
  client-payload:
    description: "JSON payload passed to the downstream workflow dispatch"
    required: false
    default: "{}"
  result-heading:
    description: "Heading to use in the formatted summary output"
    required: false
    default: "Ran ecosystem CI"
  job-name-prefix:
    description: "Job name prefix to match when summarizing downstream jobs"
    required: false
    default: "execute-all "

outputs:
  workflow-id:
    description: "ID of the triggered downstream workflow run"
    value: ${{ steps.eco_ci.outputs.workflow_id }}
  workflow-url:
    description: "URL of the triggered downstream workflow run"
    value: ${{ steps.eco_ci.outputs.workflow_url }}
  conclusion:
    description: "Conclusion reported by the downstream workflow"
    value: ${{ steps.eco_ci.outputs.conclusion }}
  summary:
    description: "Formatted markdown summary of downstream job results"
    value: ${{ steps.eco-ci-result.outputs.summary }}
  results:
    description: "JSON payload describing downstream workflow run and suites"
    value: ${{ steps.eco-ci-result.outputs.results }}

runs:
  using: composite
  steps:
    - name: Run Ecosystem CI with notify
      id: eco_ci
      continue-on-error: true
      uses: convictional/trigger-workflow-and-wait@f69fa9eedd3c62a599220f4d5745230e237904be # v1.6.5
      with:
        owner: rspack-contrib
        repo: rstack-ecosystem-ci
        workflow_file_name: ${{ inputs.workflow-file }}
        github_token: ${{ inputs.github-token }}
        ref: "main"
        client_payload: ${{ inputs.client-payload }}

    - name: Checkout
      if: steps.eco_ci.outcome == 'failure'
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 1

    - name: Setup Node.js
      if: steps.eco_ci.outcome == 'failure'
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 22
        package-manager-cache: false

    - name: Get CI Result
      id: eco-ci-result
      uses: rspack-contrib/rstack-ecosystem-ci/.github/actions/ecosystem-ci-result@main
      with:
        job-prefix: ${{ inputs.job-name-prefix }}
        heading: ${{ inputs.result-heading }}
        workflow-output: ${{ toJson(steps.eco_ci.outputs) }}

    - id: create-commit-comment
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
      if: steps.eco_ci.outcome == 'failure'
      name: Create Commit Comment
      with:
        script: |
          await github.rest.repos.createCommitComment({
            commit_sha: context.sha,
            owner: '${{ inputs.ecosystem-owner }}',
            repo: '${{ inputs.ecosystem-repo }}',
            body: `${{ steps.eco-ci-result.outputs.summary }}`
          })

    - name: Checkout ecosystem-ci repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: rspack-contrib/rstack-ecosystem-ci
        ref: main
        path: ecosystem-ci-repo
        fetch-depth: 1

    - name: Update Ecosystem History
      id: update-history
      shell: bash
      env:
        CLIENT_PAYLOAD: ${{ inputs.client-payload }}
        SUMMARY_MARKDOWN: ${{ steps.eco-ci-result.outputs.summary }}
        RESULTS_JSON: ${{ steps.eco-ci-result.outputs.results }}
        WORKFLOW_FILE: ${{ inputs.workflow-file }}
        HISTORY_REPOSITORY: rspack-contrib/rstack-ecosystem-ci
        OUTPUT_DIR: data-artifacts
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        node "$GITHUB_WORKSPACE/ecosystem-ci-repo/scripts/update-ecosystem-history.mjs"

    - name: Publish History
      if: ${{ steps.update-history.outcome == 'success' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: data
        folder: data-artifacts
        clean: false
        target-folder: .
        token: ${{ inputs.github-token }}
        repository-name: rspack-contrib/rstack-ecosystem-ci
        git-config-name: github-actions[bot]
        git-config-email: github-actions[bot]@users.noreply.github.com
