name: 'Record Ecosystem History'
description: 'Checkout repo, update ecosystem history data, and publish to GitHub Pages data branch'

inputs:
  stack:
    description: 'Stack name used when updating history'
    required: true
  source-repo:
    description: 'Source repository to include in the history metadata'
    required: true
  source-ref:
    description: 'Commit SHA or ref that triggered the history update'
    required: true
  github-token:
    description: 'Token with write access to publish the history'
    required: true
  node-version:
    description: 'Node.js version used during the update'
    required: false
    default: '22'
  output-dir:
    description: 'Directory where the generated history artifacts are stored'
    required: false
    default: 'data-artifacts'
  deploy-branch:
    description: 'Branch to publish the generated history to'
    required: false
    default: 'data'
  deploy-target-folder:
    description: 'Target folder relative to the deploy branch root'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - run: pnpm install --frozen-lockfile
      shell: bash

    - name: Update data history
      shell: bash
      env:
        STACK: ${{ inputs.stack }}
        SOURCE_REPO: ${{ inputs.source-repo }}
        SOURCE_COMMIT: ${{ inputs.source-ref }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: node ./scripts/update-ecosystem-history.mjs

    - name: Publish history
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: ${{ inputs.deploy-branch }}
        folder: ${{ inputs.output-dir }}
        clean: false
        target-folder: ${{ inputs.deploy-target-folder }}
        token: ${{ inputs.github-token }}
