name: 'Build Rsdoctor'
description: 'Checkout and install rsdoctor'
inputs:
  repository:
    description: 'The rsdoctor repository to use'
    required: true
    default: 'web-infra-dev/rsdoctor'
  path:
    description: 'Destination path to the rsdoctor repository'
    required: true
    default: 'workspace/rsdoctor'
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: true
    default: 'main'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - shell: bash
      name: Install package manager
      run: |
        npm install -g corepack@latest --force
        echo "Corepack version: $(corepack --version)"
        corepack enable

    - name: Checkout Rsdoctor repo
      uses: actions/checkout@v5
      with:
        repository: ${{ inputs.repository }}
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ inputs.path }}
        pnpm install
